/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import garnerlee.Cq;

import static org.junit.Assert.*;

public class CqTest {
	// Handle Command is basically main, for the purposes of testing.
	
	@Test public void testHandleCommandEmpty() {
        assertTrue("handleCommand query should return 'true'", Cq.handleCommand(null));
    }
	
    @Test public void testHandleCommandQuery() {
        String[] args = {"query", "query.json"};
        
        assertTrue("handleCommand query should return 'true'", Cq.handleCommand(args));
    }
    
    @Test public void testHandleCommandEmptyQuery() {
        String[] args = {"query", "empty_query.json", "data_thief_results.json"};
        
        assertTrue("handleCommand query should return 'true'", Cq.handleCommand(args));
    }
    
    @Test public void testHandleCommandQuery2() {
        String[] args = {"query", "query.json", "somewhere_else_result.json"};

        assertTrue("handleCommand query should return 'true'", Cq.handleCommand(args));
    }
    
    /* This is a more utility and test case. This is just cleanup in the challenge problem. */
    /*@Test public void testDoWipe() {
    	String[] args = {"wipe", "IAMREALLYSURE"};
    	assertTrue("handleCommand query should return 'true'", Cq.handleCommand(args));
    }*/
}
